import re
from pathlib import Path

from vibrava.clips.index import ClipIndex

STOP_WORDS = {
    "a", "an", "the", "and", "or", "but", "in", "on", "at", "to", "for",
    "of", "with", "by", "from", "is", "was", "are", "were", "be", "been",
    "have", "has", "had", "do", "does", "did", "will", "would", "could",
    "should", "may", "might", "it", "its", "this", "that", "these", "those",
    "i", "me", "my", "we", "our", "you", "your", "he", "she", "they", "their",
    "his", "her", "what", "which", "who", "how", "when", "where", "why",
    "not", "no", "so", "as", "if", "then", "than", "very", "just", "also",
    "s", "t", "re", "ve", "ll", "d",  # contraction fragments
}

# Maps common nouns and verbs to clip tags they imply.
# Keys are words that might appear in sentence text; values are tags to add
# to the search when that word is present.
WORD_TAG_MAP: dict[str, list[str]] = {
    # ------------------------------------------------------------------ #
    # sleep / rest                                                         #
    # ------------------------------------------------------------------ #
    "sleep": ["sleeping", "nap", "cozy", "tired"],
    "sleeping": ["sleeping", "nap", "cozy", "tired"],
    "asleep": ["sleeping", "nap", "cozy", "tired"],
    "nap": ["sleeping", "nap", "cozy", "tired"],
    "napping": ["sleeping", "nap", "cozy", "tired"],
    "rest": ["sleeping", "cozy", "relaxed"],
    "resting": ["sleeping", "cozy", "relaxed"],
    "dream": ["sleeping", "cozy", "nap"],
    "dreaming": ["sleeping", "cozy", "nap"],
    "doze": ["sleeping", "nap", "cozy", "tired"],
    "dozing": ["sleeping", "nap", "cozy", "tired"],
    "snooze": ["sleeping", "nap", "cozy", "tired"],
    "snoozing": ["sleeping", "nap", "cozy", "tired"],
    "loaf": ["loaf", "sitting", "calm", "relaxed"],
    "loafing": ["loaf", "sitting", "calm", "relaxed"],
    "stretch": ["stretching", "waking", "cozy", "relaxed"],
    "stretching": ["stretching", "waking", "cozy", "relaxed"],
    "stretched": ["stretching", "waking", "cozy", "relaxed"],
    "yawn": ["yawning", "tired", "waking", "sleepy"],
    "yawning": ["yawning", "tired", "waking", "sleepy"],
    "wake": ["waking", "alert", "morning"],
    "waking": ["waking", "alert", "morning"],
    "woke": ["waking", "alert", "morning"],
    # ------------------------------------------------------------------ #
    # food / eating / hunger                                               #
    # ------------------------------------------------------------------ #
    "eat": ["eating", "food", "hungry", "bowl"],
    "eating": ["eating", "food", "hungry", "bowl"],
    "ate": ["eating", "food", "hungry", "bowl"],
    "food": ["eating", "food", "bowl", "hungry"],
    "hungry": ["hungry", "eating", "food", "bowl"],
    "hunger": ["hungry", "eating", "food", "bowl"],
    "treat": ["treat", "food", "eating", "happy"],
    "treats": ["treat", "food", "eating", "happy"],
    "bowl": ["bowl", "food", "eating"],
    "snack": ["food", "eating", "treat"],
    "snacking": ["food", "eating", "treat"],
    "drink": ["drinking", "water", "bowl", "thirsty"],
    "drinking": ["drinking", "water", "bowl", "thirsty"],
    "drank": ["drinking", "water", "bowl", "thirsty"],
    "water": ["water", "drinking", "bowl", "thirsty"],
    "thirsty": ["thirsty", "drinking", "water", "bowl"],
    "kibble": ["kibble", "food", "eating", "bowl"],
    "chicken": ["chicken", "food", "eating", "hungry"],
    "tuna": ["tuna", "food", "eating", "treat"],
    "bite": ["eating", "food", "biting", "hungry"],
    "biting": ["eating", "food", "biting", "aggressive"],
    "chew": ["eating", "food", "chewing"],
    "chewing": ["eating", "food", "chewing"],
    "devour": ["eating", "food", "hungry", "fast"],
    "devouring": ["eating", "food", "hungry", "fast"],
    # ------------------------------------------------------------------ #
    # movement / speed                                                     #
    # ------------------------------------------------------------------ #
    "run": ["running", "fast", "chase", "escape"],
    "running": ["running", "fast", "chase", "escape"],
    "ran": ["running", "fast", "chase", "escape"],
    "sprint": ["running", "fast", "zoomies", "energetic"],
    "sprinting": ["running", "fast", "zoomies", "energetic"],
    "dash": ["running", "fast", "escape", "zoomies"],
    "dashing": ["running", "fast", "escape", "zoomies"],
    "bolt": ["running", "fast", "escape", "scared"],
    "bolting": ["running", "fast", "escape", "scared"],
    "flee": ["running", "escape", "scared", "fast"],
    "fleeing": ["running", "escape", "scared", "fast"],
    "zoom": ["running", "fast", "zoomies", "playful"],
    "zooming": ["running", "fast", "zoomies", "playful"],
    "zoomies": ["zoomies", "running", "fast", "playful"],
    "jump": ["jumping", "athletic", "high", "playful"],
    "jumping": ["jumping", "athletic", "high", "playful"],
    "jumped": ["jumping", "athletic", "high", "playful"],
    "leap": ["jumping", "athletic", "high"],
    "leaping": ["jumping", "athletic", "high"],
    "leaped": ["jumping", "athletic", "high"],
    "pounce": ["pouncing", "jumping", "hunting", "playful"],
    "pouncing": ["pouncing", "jumping", "hunting", "playful"],
    "pounced": ["pouncing", "jumping", "hunting", "playful"],
    "climb": ["climbing", "high", "athletic", "tree"],
    "climbing": ["climbing", "high", "athletic", "tree"],
    "climbed": ["climbing", "high", "athletic", "tree"],
    "walk": ["walking", "calm", "inside", "floor"],
    "walking": ["walking", "calm", "inside", "floor"],
    "walked": ["walking", "calm", "inside", "floor"],
    "pace": ["pacing", "anxious", "inside", "floor"],
    "pacing": ["pacing", "anxious", "inside", "floor"],
    "chase": ["chase", "running", "playful", "hunting"],
    "chasing": ["chase", "running", "playful", "hunting"],
    "chased": ["chase", "running", "playful", "hunting"],
    "teleport": ["running", "fast", "escape", "zoomies"],
    "teleported": ["running", "fast", "escape", "zoomies"],
    "escape": ["escape", "running", "hiding", "sneaky"],
    "escaping": ["escape", "running", "hiding", "sneaky"],
    "escaped": ["escape", "running", "hiding", "sneaky"],
    "slip": ["sneaky", "escape", "fast", "floor"],

    "slipping": ["sneaky", "escape", "fast", "floor"],
    "slipped": ["sneaky", "escape", "fast", "floor"],
    # ------------------------------------------------------------------ #
    # hiding / stealth / hunting                                           #
    # ------------------------------------------------------------------ #
    "hide": ["hiding", "sneaky", "under", "cozy"],
    "hiding": ["hiding", "sneaky", "under", "cozy"],
    "hid": ["hiding", "sneaky", "under"],
    "sneak": ["sneaky", "hiding", "quiet"],
    "sneaking": ["sneaky", "hiding", "quiet"],
    "sneaked": ["sneaky", "hiding", "quiet"],
    "lurk": ["lurking", "sneaky", "hiding", "focused"],
    "lurking": ["lurking", "sneaky", "hiding", "focused"],
    "stalk": ["stalking", "sneaky", "hunting", "focused"],
    "stalking": ["stalking", "sneaky", "hunting", "focused"],
    "hunt": ["hunting", "stalking", "focused", "sneaky"],
    "hunting": ["hunting", "stalking", "focused", "sneaky"],
    "ambush": ["ambush", "hunting", "sneaky", "jumping"],
    "ambushing": ["ambush", "hunting", "sneaky", "jumping"],
    "spy": ["watching", "sneaky", "focused", "curious"],
    "spying": ["watching", "sneaky", "focused", "curious"],
    "crouch": ["crouching", "sneaky", "hunting", "low"],
    "crouching": ["crouching", "sneaky", "hunting", "low"],
    "crouched": ["crouching", "sneaky", "hunting", "low"],
    # ------------------------------------------------------------------ #
    # staring / watching / awareness                                       #
    # ------------------------------------------------------------------ #
    "stare": ["staring", "intense", "focused", "eyes"],
    "staring": ["staring", "intense", "focused", "eyes"],
    "stared": ["staring", "intense", "focused"],
    "glare": ["staring", "intense", "angry", "eyes"],
    "glaring": ["staring", "intense", "angry", "eyes"],
    "watch": ["watching", "focused", "window", "curious"],
    "watching": ["watching", "focused", "window", "curious"],
    "look": ["watching", "curious", "focused"],
    "looking": ["watching", "curious", "focused"],
    "notice": ["alert", "focused", "watching", "curious"],
    "noticed": ["alert", "focused", "watching", "curious"],
    "spot": ["alert", "focused", "watching", "hunting"],
    "spotted": ["alert", "focused", "watching", "hunting"],
    "see": ["watching", "curious", "focused", "eyes"],
    "saw": ["watching", "curious", "focused", "eyes"],
    "seen": ["watching", "curious", "focused", "eyes"],
    "observe": ["watching", "focused", "calm", "curious"],
    "observing": ["watching", "focused", "calm", "curious"],
    "peek": ["curious", "hiding", "sneaky", "watching"],
    "peeking": ["curious", "hiding", "sneaky", "watching"],
    "peered": ["curious", "watching", "focused", "eyes"],
    "peering": ["curious", "watching", "focused", "eyes"],
    "ignore": ["ignoring", "smug", "calm", "unbothered"],
    "ignoring": ["ignoring", "smug", "calm", "unbothered"],
    "ignored": ["ignoring", "smug", "calm", "unbothered"],
    # ------------------------------------------------------------------ #
    # sitting / posing / stillness                                         #
    # ------------------------------------------------------------------ #
    "sit": ["sitting", "loaf", "calm", "relaxed"],
    "sitting": ["sitting", "loaf", "calm", "relaxed"],
    "sat": ["sitting", "loaf", "calm"],
    "pose": ["sitting", "calm", "smug"],
    "posing": ["sitting", "calm", "smug"],
    "perch": ["perching", "high", "sitting", "watching"],
    "perching": ["perching", "high", "sitting", "watching"],
    "perched": ["perching", "high", "sitting", "watching"],
    "curl": ["curled", "sleeping", "cozy", "nap"],
    "curled": ["curled", "sleeping", "cozy", "nap"],
    "curling": ["curled", "sleeping", "cozy", "nap"],
    "knead": ["kneading", "happy", "cozy", "content"],
    "kneading": ["kneading", "happy", "cozy", "content"],
    "biscuits": ["kneading", "happy", "cozy", "content"],
    "roll": ["rolling", "playful", "floor", "happy"],
    "rolling": ["rolling", "playful", "floor", "happy"],
    "rolled": ["rolling", "playful", "floor", "happy"],
    "flop": ["flopped", "relaxed", "floor", "cozy"],
    "flopped": ["flopped", "relaxed", "floor", "cozy"],
    "flopping": ["flopped", "relaxed", "floor", "cozy"],
    # ------------------------------------------------------------------ #
    # locations / furniture / objects                                      #
    # ------------------------------------------------------------------ #
    "bed": ["bed", "sleeping", "cozy", "furniture"],
    "pillow": ["pillow", "sleeping", "cozy", "bed"],
    "blanket": ["blanket", "cozy", "sleeping", "warm"],
    "couch": ["couch", "furniture", "cozy", "relaxed"],
    "sofa": ["couch", "furniture", "cozy", "relaxed"],
    "chair": ["chair", "furniture", "sitting", "perching"],
    "shelf": ["shelf", "high", "perching", "furniture"],
    "counter": ["counter", "high", "furniture", "naughty"],
    "table": ["table", "furniture", "high", "naughty"],
    "window": ["window", "outside", "curious", "watching"],
    "sill": ["window", "outside", "curious", "perching"],
    "door": ["door", "outside", "curious", "escape"],
    "box": ["box", "cozy", "hiding", "curious"],
    "bag": ["bag", "hiding", "curious", "sneaky"],
    "drawer": ["furniture", "hiding", "sneaky", "inside"],
    "basket": ["basket", "cozy", "hiding", "sleeping"],
    "floor": ["floor", "inside", "loaf", "sitting"],
    "carpet": ["carpet", "floor", "inside", "scratching"],
    "rug": ["rug", "floor", "inside", "cozy"],
    "sink": ["sink", "water", "curious", "naughty"],
    "toilet": ["toilet", "water", "curious", "naughty"],
    "outside": ["outside", "window", "curious", "freedom"],
    "garden": ["outside", "nature", "curious", "freedom"],
    "yard": ["outside", "nature", "curious", "running"],
    "tree": ["outside", "climbing", "nature", "curious"],
    "grass": ["outside", "nature", "freedom", "rolling"],
    "stairs": ["stairs", "inside", "running", "perching"],
    "closet": ["hiding", "inside", "cozy", "dark"],
    "laundry": ["hiding", "cozy", "inside", "sneaky"],
    "cave": ["hiding", "cozy", "dark", "sleeping"],
    "tunnel": ["hiding", "cozy", "sneaky", "playful"],
    "carrier": ["carrier", "vet", "scared", "trapped"],
    "cage": ["carrier", "vet", "scared", "trapped"],
    # ------------------------------------------------------------------ #
    # play / toys / energy                                                 #
    # ------------------------------------------------------------------ #
    "play": ["playing", "playful", "toy", "energetic"],
    "playing": ["playing", "playful", "toy", "energetic"],
    "played": ["playing", "playful", "toy"],
    "toy": ["toy", "playing", "playful", "hunting"],
    "toys": ["toy", "playing", "playful", "hunting"],
    "wand": ["wand", "toy", "playing", "playful"],
    "feather": ["feather", "toy", "playing", "hunting"],
    "laser": ["laser", "toy", "playing", "chase"],
    "string": ["string", "toy", "playing", "hunting"],
    "ball": ["ball", "toy", "playing", "rolling"],
    "bat": ["playing", "toy", "paw", "playful"],
    "batting": ["playing", "toy", "paw", "playful"],
    "swat": ["swatting", "paw", "playing", "hunting"],
    "swatting": ["swatting", "paw", "playing", "hunting"],
    "swatted": ["swatting", "paw", "playing", "hunting"],
    "paw": ["paw", "playing", "touching", "curious"],
    "pawing": ["paw", "playing", "touching", "curious"],
    "tap": ["tap", "paw", "playing", "curious"],
    "tapping": ["tap", "paw", "playing", "curious"],
    "attack": ["attacking", "playing", "hunting", "aggressive"],
    "attacking": ["attacking", "playing", "hunting", "aggressive"],
    "attacked": ["attacking", "playing", "hunting", "aggressive"],
    "wrestle": ["wrestling", "playing", "fighting", "energetic"],
    "wrestling": ["wrestling", "playing", "fighting", "energetic"],
    # ------------------------------------------------------------------ #
    # grooming / claws / hygiene                                           #
    # ------------------------------------------------------------------ #
    "groom": ["grooming", "clean", "lick", "bath"],
    "grooming": ["grooming", "clean", "lick", "bath"],
    "lick": ["grooming", "lick", "clean", "bath"],
    "licking": ["grooming", "lick", "clean", "bath"],
    "licked": ["grooming", "lick", "clean", "bath"],
    "bath": ["grooming", "clean", "lick", "bath"],
    "bathing": ["grooming", "clean", "lick", "bath"],
    "clean": ["grooming", "clean", "lick", "bath"],
    "cleaning": ["grooming", "clean", "lick", "bath"],
    "scratch": ["scratch", "claws", "naughty", "furniture"],
    "scratching": ["scratch", "claws", "naughty", "furniture"],
    "scratched": ["scratch", "claws", "naughty"],
    "claw": ["claws", "scratch", "naughty"],
    "claws": ["claws", "scratch", "naughty"],
    "nails": ["claws", "grooming", "naughty"],
    "clip": ["claws", "grooming", "vet", "scared"],
    "clipping": ["claws", "grooming", "vet", "scared"],
    "trim": ["claws", "grooming", "vet", "scared"],
    "trimming": ["claws", "grooming", "vet", "scared"],
    "sharpening": ["scratch", "claws", "naughty", "furniture"],
    # ------------------------------------------------------------------ #
    # emotions / moods / states                                            #
    # ------------------------------------------------------------------ #
    "angry": ["angry", "grumpy", "ears", "hissing"],
    "anger": ["angry", "grumpy", "ears", "hissing"],
    "mad": ["angry", "grumpy", "upset"],
    "furious": ["angry", "hissing", "ears", "aggressive"],
    "grumpy": ["grumpy", "angry", "tired", "ears"],
    "annoyed": ["grumpy", "angry", "tail", "ears"],
    "upset": ["upset", "angry", "grumpy", "sad"],
    "scared": ["scared", "hiding", "wide", "eyes"],
    "afraid": ["scared", "hiding", "wide", "eyes"],
    "terrified": ["scared", "hiding", "wide", "eyes"],
    "nervous": ["scared", "anxious", "hiding", "alert"],
    "anxious": ["anxious", "scared", "pacing", "alert"],
    "startled": ["scared", "alert", "jumping", "eyes"],
    "happy": ["happy", "playful", "purring", "cozy"],
    "excited": ["excited", "playful", "energetic", "happy"],
    "content": ["content", "purring", "cozy", "relaxed"],
    "pleased": ["content", "smug", "purring", "relaxed"],
    "smug": ["smug", "sitting", "calm", "winning"],
    "proud": ["smug", "sitting", "calm", "winning"],
    "superior": ["smug", "sitting", "calm", "unbothered"],
    "unbothered": ["unbothered", "smug", "calm", "ignoring"],
    "bored": ["bored", "sitting", "staring", "tired"],
    "curious": ["curious", "watching", "alert", "sniffing"],
    "confused": ["confused", "head-tilt", "curious", "alert"],
    "victory": ["smug", "winning", "calm", "sitting"],
    "winning": ["smug", "winning", "calm"],
    "defeated": ["sad", "hiding", "quiet", "floor"],
    "betrayed": ["sad", "upset", "staring", "intense"],
    "offended": ["grumpy", "smug", "tail", "turning"],
    "dramatic": ["dramatic", "flopped", "staring", "upset"],
    "peaceful": ["calm", "cozy", "sleeping", "relaxed"],
    "cozy": ["cozy", "sleeping", "warm", "content"],
    "warm": ["warm", "cozy", "sleeping", "sunny"],
    "cold": ["cold", "cozy", "blanket", "curled"],
    "tired": ["tired", "sleeping", "yawning", "slow"],
    "exhausted": ["tired", "sleeping", "nap", "floor"],
    "energetic": ["energetic", "playful", "zoomies", "running"],
    "feral": ["feral", "wild", "aggressive", "hunting"],
    "menacing": ["intense", "staring", "focused", "hunting"],
    # ------------------------------------------------------------------ #
    # sounds / vocalizations                                               #
    # ------------------------------------------------------------------ #
    "meow": ["meowing", "talking", "loud", "vocal"],
    "meowing": ["meowing", "talking", "loud", "vocal"],
    "meowed": ["meowing", "talking", "loud", "vocal"],
    "hiss": ["hissing", "angry", "scared", "ears"],
    "hissing": ["hissing", "angry", "scared", "ears"],
    "hissed": ["hissing", "angry", "scared", "ears"],
    "purr": ["purring", "happy", "cozy", "content"],
    "purring": ["purring", "happy", "cozy", "content"],
    "purred": ["purring", "happy", "cozy", "content"],
    "chirp": ["chirping", "bird", "window", "excited"],
    "chirping": ["chirping", "bird", "window", "excited"],
    "chirped": ["chirping", "bird", "window", "excited"],
    "chatter": ["chattering", "bird", "window", "excited"],
    "chattering": ["chattering", "bird", "window", "excited"],
    "growl": ["growling", "angry", "aggressive", "warning"],
    "growling": ["growling", "angry", "aggressive", "warning"],
    "yowl": ["yowling", "loud", "upset", "vocal"],
    "yowling": ["yowling", "loud", "upset", "vocal"],
    "scream": ["yowling", "loud", "scared", "chaos"],
    "screaming": ["yowling", "loud", "scared", "chaos"],
    "trill": ["trilling", "happy", "vocal", "friendly"],
    "trilling": ["trilling", "happy", "vocal", "friendly"],
    "silent": ["quiet", "hiding", "sneaky", "calm"],
    # ------------------------------------------------------------------ #
    # body parts / physical                                                #
    # ------------------------------------------------------------------ #
    "tail": ["tail", "mood", "wagging", "annoyed"],
    "ears": ["ears", "alert", "angry", "listening"],
    "eyes": ["eyes", "staring", "focused", "intense"],
    "paws": ["paw", "playing", "touching", "grooming"],
    "belly": ["belly", "cute", "relaxed", "trust"],
    "fur": ["fur", "grooming", "fluffy", "soft"],
    "whiskers": ["whiskers", "curious", "alert", "sensing"],
    "nose": ["nose", "sniffing", "curious", "alert"],
    "teeth": ["teeth", "yawning", "hissing", "eating"],
    "tongue": ["licking", "grooming", "eating", "silly"],
    # ------------------------------------------------------------------ #
    # humans / other animals / social                                      #
    # ------------------------------------------------------------------ #
    "human": ["human", "owner", "person"],
    "owner": ["human", "owner", "person"],
    "person": ["human", "owner", "person"],
    "people": ["human", "owner", "person"],
    "mom": ["human", "owner", "person"],
    "dad": ["human", "owner", "person"],
    "baby": ["baby", "human", "small", "curious"],
    "child": ["baby", "human", "small", "curious"],
    "stranger": ["stranger", "scared", "hiding", "alert"],
    "guest": ["stranger", "hiding", "curious", "alert"],
    "visitor": ["stranger", "hiding", "curious", "alert"],
    "vet": ["vet", "scared", "carrier", "unhappy"],
    "doctor": ["vet", "scared", "carrier", "unhappy"],
    "dog": ["dog", "chase", "scared", "running"],
    "puppy": ["dog", "chase", "curious", "playful"],
    "bird": ["bird", "outside", "window", "hunting"],
    "mouse": ["mouse", "hunting", "toy", "chase"],
    "squirrel": ["squirrel", "outside", "window", "hunting"],
    "bug": ["bug", "hunting", "curious", "floor"],
    "insect": ["bug", "hunting", "curious", "floor"],
    "fly": ["bug", "hunting", "jumping", "curious"],
    "spider": ["bug", "hunting", "curious", "scared"],
    "butterfly": ["butterfly", "outside", "hunting", "curious"],
    "fish": ["fish", "food", "eating", "hunting", "water", "watching"],
    # ------------------------------------------------------------------ #
    # time / environment                                                   #
    # ------------------------------------------------------------------ #
    "morning": ["morning", "waking", "sunny", "window"],
    "night": ["night", "dark", "zoomies", "sneaky"],
    "midnight": ["night", "dark", "zoomies", "sneaky"],
    "noon": ["sunny", "warm", "sleeping", "cozy"],
    "afternoon": ["sunny", "warm", "nap", "cozy"],
    "evening": ["evening", "cozy", "calm", "window"],
    "monday": ["tired", "grumpy", "sleeping", "morning"],
    "sun": ["sunny", "warm", "window", "cozy"],
    "sunny": ["sunny", "warm", "window", "sleeping"],
    "rain": ["rain", "inside", "window", "watching"],
    "raining": ["rain", "inside", "window", "watching"],
    "snow": ["snow", "window", "curious", "cold"],
    "snowing": ["snow", "window", "curious", "cold"],
    "dark": ["dark", "night", "sneaky", "hiding"],
    "darkness": ["dark", "night", "sneaky", "hiding"],
    "quiet": ["quiet", "calm", "sneaky", "hiding"],
    "chaos": ["chaos", "zoomies", "running", "playful", "energetic"],
    # ------------------------------------------------------------------ #
    # actions / verbs (misc)                                               #
    # ------------------------------------------------------------------ #
    "bring": ["carrying", "hunting", "proud", "showing"],
    "brought": ["carrying", "hunting", "proud", "showing"],
    "drop": ["dropping", "playing", "hunting", "showing"],
    "dropped": ["dropping", "playing", "hunting", "showing"],
    "push": ["pushing", "paw", "naughty", "floor"],
    "pushing": ["pushing", "paw", "naughty", "floor"],
    "pushed": ["pushing", "paw", "naughty", "floor"],
    "knock": ["knocking", "paw", "naughty", "chaos"],
    "knocking": ["knocking", "paw", "naughty", "chaos"],
    "knocked": ["knocking", "paw", "naughty", "chaos"],
    "steal": ["stealing", "sneaky", "naughty", "food"],
    "stealing": ["stealing", "sneaky", "naughty", "food"],
    "stole": ["stealing", "sneaky", "naughty", "food"],
    "demand": ["meowing", "vocal", "hungry", "loud"],
    "demanding": ["meowing", "vocal", "hungry", "loud"],
    "demanded": ["meowing", "vocal", "hungry", "loud"],
    "wait": ["waiting", "sitting", "focused", "patient"],
    "waiting": ["waiting", "sitting", "focused", "patient"],
    "waited": ["waiting", "sitting", "focused", "patient"],
    "judge": ["judging", "staring", "intense", "smug"],
    "judging": ["judging", "staring", "intense", "smug"],
    "judged": ["judging", "staring", "intense", "smug"],
    "refuse": ["refusing", "smug", "unbothered", "sitting"],
    "refusing": ["refusing", "smug", "unbothered", "sitting"],
    "refused": ["refusing", "smug", "unbothered", "sitting"],
    "accept": ["happy", "content", "calm", "receiving"],
    "accepted": ["happy", "content", "calm", "receiving"],
    "headbutt": ["headbutt", "affectionate", "friendly", "happy"],
    "headbutting": ["headbutt", "affectionate", "friendly", "happy"],
    "nuzzle": ["nuzzle", "affectionate", "friendly", "happy"],
    "nuzzling": ["nuzzle", "affectionate", "friendly", "happy"],
    "rub": ["rubbing", "affectionate", "marking", "friendly"],
    "rubbing": ["rubbing", "affectionate", "marking", "friendly"],
    "follow": ["following", "curious", "friendly", "watching"],
    "following": ["following", "curious", "friendly", "watching"],
    "followed": ["following", "curious", "friendly", "watching"],
    "search": ["searching", "curious", "focused", "sniffing"],
    "searching": ["searching", "curious", "focused", "sniffing"],
    "find": ["searching", "curious", "focused", "hunting"],
    "finding": ["searching", "curious", "focused", "hunting"],
    "found": ["searching", "curious", "focused", "hunting"],
    "sniff": ["sniffing", "curious", "alert", "nose"],
    "sniffing": ["sniffing", "curious", "alert", "nose"],
    "sniffed": ["sniffing", "curious", "alert", "nose"],
    "explore": ["exploring", "curious", "sniffing", "walking"],
    "exploring": ["exploring", "curious", "sniffing", "walking"],
    "explored": ["exploring", "curious", "sniffing", "walking"],
    "vanish": ["hiding", "sneaky", "escape", "fast"],
    "vanished": ["hiding", "sneaky", "escape", "fast"],
    "disappear": ["hiding", "sneaky", "escape", "fast"],
    "disappeared": ["hiding", "sneaky", "escape", "fast"],
    "protect": ["guarding", "sitting", "alert", "focused"],
    "protecting": ["guarding", "sitting", "alert", "focused"],
    "guard": ["guarding", "sitting", "alert", "focused"],
    "guarding": ["guarding", "sitting", "alert", "focused"],
    "win": ["winning", "smug", "calm", "victory"],
    "won": ["winning", "smug", "calm", "victory"],
    "lose": ["defeated", "sad", "quiet", "hiding"],
    "lost": ["defeated", "sad", "quiet", "hiding"],
    "survive": ["winning", "smug", "calm", "escape"],
    "survived": ["winning", "smug", "calm", "escape"],
    "suffer": ["dramatic", "sad", "upset", "flopped"],
    "suffering": ["dramatic", "sad", "upset", "flopped"],
    "tolerate": ["smug", "unbothered", "calm", "grumpy"],
    "tolerating": ["smug", "unbothered", "calm", "grumpy"],
    "tolerated": ["smug", "unbothered", "calm", "grumpy"],
    "celebrate": ["happy", "excited", "playful", "winning"],
    "celebrating": ["happy", "excited", "playful", "winning"],
    "celebrated": ["happy", "excited", "playful", "winning"],
}


def extract_tags(text: str) -> list[str]:
    words = re.findall(r"[a-z]+", text.lower())
    return [w for w in words if w not in STOP_WORDS]


def expand_tags(words: list[str]) -> list[str]:
    """Add semantic tags implied by common nouns/verbs in *words*.

    Returns the original words plus any mapped tags, deduplicated while
    preserving order (originals first).
    """
    seen: set[str] = set(words)
    result = list(words)
    for word in words:
        for tag in WORD_TAG_MAP.get(word, []):
            if tag not in seen:
                seen.add(tag)
                result.append(tag)
    return result


def match(
    text: str,
    index: ClipIndex,
    extra_tags: list[str] | None = None,
) -> Path | None:
    results = match_many(text, index, n=1, extra_tags=extra_tags)
    return results[0] if results else None


def match_many(
    text: str,
    index: ClipIndex,
    n: int = 1,
    extra_tags: list[str] | None = None,
) -> list[Path]:
    tags = expand_tags(extract_tags(text))
    if extra_tags:
        seen = set(tags)
        for t in extra_tags:
            if t not in seen:
                seen.add(t)
                tags.append(t)
    results = index.find_by_tags(tags)
    return [index.resolve_path(r) for r in results[:n]]
